"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from typing import List

from esmerald import delete, get, Inject, Injects, post
from esmerald.openapi.datastructures import OpenAPIResponse

from blog.apps.accounts.v1.daos import UserDAO
from blog.apps.accounts.v1.schemas import Error, UserIn, UserOut


@get(
    "/users",
    tags=["User"],
    description="List of all the users in the system",
    summary="Lists all users",
    responses={
        200: OpenAPIResponse(model=[UserOut]),
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def users(user_dao: UserDAO) -> List[UserOut]:
    """
    Lists all the users in the system.
    """
    return await user_dao.get_all()


@get(
    "/user/{id}",
    tags=["User"],
    summary="Get a user",
    description="Shows the information of a user",
    responses={
        200: OpenAPIResponse(model=UserOut),
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def user(id: int, user_dao: UserDAO) -> UserOut:
    """
    Get the information about a user
    """
    return await user_dao.get(obj_id=id)


@post(
    "/create",
    tags=["User"],
    summary="Create a user",
    description="Creates a user in the system",
    responses={400: OpenAPIResponse(model=Error, description="Bad response")},
)
async def create(data: UserIn, user_dao: UserDAO) -> None:
    """
    Creates a user in the system.
    """
    await user_dao.create(**data.model_dump())


@delete(
    "/user/{id}",
    summary="Delete a user",
    tags=["User"],
    description="Deletes a user from the system by ID",
    responses={
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def delete_user(id: int, user_dao: UserDAO) -> None:
    """
    Deletes a user.
    """
    await user_dao.delete(obj_id=id)
