#!/usr/bin/env python
"""
Generated by 'esmerald createproject' using Esmerald 2.0.5.
"""
import os
import sys
from typing import Optional

from esmerald import Esmerald, Include, Inject, settings
from esmerald.exception_handlers import value_error_handler
from esmerald_admin import Admin
from esmerald_admin.backends.saffier.email import EmailAdminAuth
from saffier import Database, Migrate, Registry

from blog.apps.accounts.v1.daos import UserDAO
from blog.apps.articles.v1.daos import ArticleDAO
from blog.apps.posts.v1.daos import PostDAO

database, registry = settings.db_access

SITE_ROOT = os.path.dirname(os.path.realpath(__file__))


def build_path():
    """
    Builds the path of the project and project root.
    """
    if SITE_ROOT not in sys.path:
        sys.path.append(SITE_ROOT)
        sys.path.append(os.path.join(SITE_ROOT, "apps"))


def get_migrations(app_: Esmerald, registry_: Registry) -> None:
    """
    Activates the migration system of Saffier with Esmerald
    """
    Migrate(app=app_, registry=registry_)


def get_admin(app_: Esmerald, registry_: Registry) -> None:
    """
    Starts the admin
    """
    from blog.admin import get_views
    from blog.apps.accounts.models import User

    auth_backend = EmailAdminAuth(
        secret_key=settings.secret_key, auth_model=User, config=settings.jwt_config
    )

    admin = Admin(app_, registry_.engine, authentication_backend=auth_backend)

    # Get the views function from the "admin.py"
    get_views(admin)


def get_application(
    connection: Optional[Database] = None, models: Optional[Registry] = None
):
    """
    This is optional. The function is only used for organisation purposes.
    """
    build_path()

    db = connection or database
    app_ = Esmerald(
        routes=[Include(namespace="blog.urls")],
        on_startup=[db.connect],
        on_shutdown=[db.disconnect],
        exception_handlers={ValueError: value_error_handler},
        dependencies={
            "user_dao": Inject(lambda: UserDAO()),
            "article_dao": Inject(lambda: ArticleDAO()),
            "post_dao": Inject(lambda: PostDAO()),
        },
    )

    # Migrations
    db_registry = models or registry
    get_migrations(app_=app_, registry_=db_registry)

    # Admin
    get_admin(app_=app_, registry_=db_registry)
    return app_


app = get_application()
