"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from typing import List

from esmerald import delete, get, post
from esmerald.openapi.datastructures import OpenAPIResponse

from blog.apps.posts.v1.daos import PostDAO
from blog.apps.posts.v1.schemas import Error, PostIn, PostOut


@get(
    "/{article_id}",
    tags=["Post"],
    description="Returns all posts of an article",
    summary="Posts of an article",
    responses={
        200: OpenAPIResponse(model=[PostOut]),
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def posts(article_id: int, post_dao: PostDAO) -> List[PostOut]:
    """
    Gets all posts.
    """
    return await post_dao.get_all(article_id=article_id)


@post(
    "/{article_id}",
    tags=["Post"],
    description="Creates a post for a specific article",
    summary="Create a post of an article",
    responses={
        200: OpenAPIResponse(model=[PostOut]),
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def create_post(data: PostIn, article_id: int, post_dao: PostDAO) -> PostOut:
    """
    Creates a post for a specfic article.
    """
    return await post_dao.create(article_id=article_id, **data.model_dump())


@delete(
    "/{article_id}/{post_id}",
    tags=["Post"],
    description="Deletes a post from the article",
    summary="Deletes a post",
    responses={
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def delete_post(article_id: int, post_id: int, post_dao: PostDAO) -> None:
    """
    Deletes a post from an article
    """
    await post_dao.delete(obj_id=post_id, article_id=article_id)
